_target_: source.datasets.extraction_datamodule.ExtractionDatamodule
_recursive_: False

batch_size: 8
num_workers: 8

dataset_name: "10474_sim"
dataset_path: "${paths.data_dir}/${datamodule.dataset_name}"
particles_star_path: "${datamodule.dataset_path}/${datamodule.dataset_name}_extract.star"
out_dir:  "${datamodule.dataset_path}/extraction/noisy"

new_size: 384
old_size: 512
bg_radius: 100
invert_contrast: True
file_mode: 'h5'
num_frames: 30

#CTF params
cs: 2.7
kv: 300
q0: 0.1
angpix: 0.706667
dose_per_frame: 1.36
pre_exposure: 0
voltage: 300

dataset:
  _target_: source.datasets.extraction_dataset.ExtractionDataset
  box: ${datamodule.old_size}